# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Cat Killed Curiousity
email: jeff@jbrr.dev
name: Jeff Ruane
description: >-
  Software engineer, just trying my best
url: https://jbrr.dev # the base hostname & protocol for your site, e.g. http://example.com
repository: jbrr/jbrr.github.io
twitter_username: jefbrr
github_username:  jbrr
locale: en-US

author:
  name: Jeff Ruane
  avatar: "/assets/images/me.jpg"
  bio: >-
    Pretty much fine software engineer, although I'm more concerned with being a good person than programming.
  location: Denver, CO
  email: jeff@jbrr.dev
  twitter: jefbrr
  github: jbrr
  links:
    - label: Keybase
      icon: "fab fa-fw fa-keybase"
      url: "https://keybase.io/jbrr"

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dirt

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-remote-theme
  - jekyll-include-cache

comments:
  provider  : staticman_v2
  staticman:
    branch    : main
    endpoint  : https://jbrr-staticman.herokuapp.com/v3/entry/github/

category_archive:
  type: jekyll-archives
  path: /categories/

tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      date_format: "%Y-%m-%d"
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
