# Site settings
title: def jef
email: ruane [dot] jb [at] gmail [dot] com
description: puts "#{sloppy_thoughts}"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jbrr.github.io" # the base hostname & protocol for your site
twitter_username: jefbrr
github_username:  jbrr

# Build settings
markdown: kramdown
