# Site settings
title: def jef
email: ruane.jb@gmail.com
description: Nude Dude with a Rude 'Tude
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jbrr.github.io" # the base hostname & protocol for your site
twitter_username: jefbrr
github_username:  jbrr
linkedin_username: jeffruane

# Build settings
markdown: kramdown
