baseURL: https://jbrr.dev/
languageCode: en-us
theme: "hugo-bearblog"

title: Jeff Ruane
author: Jeff Ruane
copyright: cc by 4.0 Jeff Ruane


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

disableKinds:
    - taxonomy
ignoreErrors:
    - error-disable-taxonomy
permalinks:
  blog: "/:slug/"
  tags: "/blog/:slug"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    description: "Hotdog guru"
    author: Jeff Ruane
    images: [/jbrr.jpg]
    hCardImage: /jbrr-512x518px.jpg

    alt_titles:
        - A Fate Worse Than Jeff
        - Nothing is Certain but Jeff and Taxes
        - Jeff is More
        - Hot off the Jeff
        - Bored to Jeff
        - 30 Minutes or Jeff
        - Jeff Metal
        - Jeff Leppard
        - Jeff Than Jake
        - The Jeff You Know, The Better
        - We Have the Facts and We're Voting Jeff
        - The Road Jeff Traveled
        - James S. Brady Jeff Briefing Room
        - Nothing Jeff Nothing More
        - Jeff Cab for Cutie
        - Blue Screen of Jeff
        - Every Jeff You Take

    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"
