[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
    NODE_VERSION = "18.x"

[functions]
    external_node_modules = ["@resvg/resvg-js", "astro"]
    directory = "dist/functions"