# Plausible Analytics proxy https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/js/script.outbound-links.js"
to = "https://plausible.io/js/script.outbound-links.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 200